### PR TITLE
Use async closure

### LINKED ISSUE #5: Use `AsyncFnOnce` instead of `FnOnce -> RetFut`
[Async closure has been stabilized in Rust 1.85](https://github.com/rust-lang/rust/pull/132706) this brings a much better ergonomic when passing reference to a closure.

For instance currently this wrapper is not possible (but would be fine if `TransactionBuilder::run` would accept an async closure):

```rust
struct WrapperDatabase {
    pub async fn for_update<R, E>(
        &mut self,
        cb: impl AsyncFnOnce(TransactionWrapper),
    ) {
        self.conn.transaction(&["store"])
            .run(async move |transaction| {
                let wrapper = TransactionWrapper(transaction);
                cb(wrapper).await
                Ok(())
            })
            .await.unwrap();
    }
}
```
Rust compilation error:
```
the parameter type `impl AsyncFnOnce(TransactionWrapper)` must be valid for the static lifetime...
...so that the type `impl AsyncFnOnce(TransactionWrapper)` will meet its required lifetime bounds
```

### PR DESCRIPTION
**Pull request by touilleMan**
close #5 

Note this constitutes a breaking change, and means only Rust>=1.85 is supported

Regarding the Rust>=1.85, another solution to avoid this would be to put async closure support under a feature.
This is a bit trick though: since `Faction::open` & `TransactionBuilder::run` would have two flavors of signature.

To do that there is basically three ways:
1. Duplicate `Faction::open` & `TransactionBuilder::run` bodies
2. Put `Faction::open` & `TransactionBuilder::run` body inside a macro which is called in each flavor of the functions
3. Have the async-closure flavor of `Faction::open` & `TransactionBuilder::run` internally calles the sync-closure -returning-future

```rust
    #[cfg(not(feature = "async-closure"))]
    pub async fn open<Fun, RetFut>(
        &self,
        name: &str,
        version: u32,
        on_upgrade_needed: Fun,
    ) -> crate::Result<Database<Err>, Err>
    where
        Fun: 'static + FnOnce(VersionChangeEvent<Err>) -> RetFut,
        RetFut: 'static + Future<Output = crate::Result<(), Err>> {
        self.open_internal(name, version, on_upgrade_needed).await
}

    #[cfg(feature = "async-closure")]
    pub async fn open(
        &self,
        name: &str,
        version: u32,
        on_upgrade_needed: impl AsyncFnOnce(VersionChangeEvent<Err>) -> crate::Result<(), Err> + 'static,
    ) -> crate::Result<Database<Err>, Err> {
        self.open_internal(name, version, |evt| on_upgrade_needed(evt)).await
    }

    async fn open_internal<Fun, RetFut>(
        &self,
        name: &str,
        version: u32,
        on_upgrade_needed: Fun,
    ) -> crate::Result<Database<Err>, Err>
    where
        Fun: 'static + FnOnce(VersionChangeEvent<Err>) -> RetFut,
        RetFut: 'static + Future<Output = crate::Result<(), Err>> {
        ...
    }
```

Solution 3 seems the most elegant, however it only works because the async closure is `'static`.

If that wasn't the case we would in theory need to use a `unsafe std::mem::transmute` to overwrite the lifetime of the async closure before passing it to `open_internal`... but even this doesn't work in practice:
- In Rust each closure has it own type (i.e. two closures with the same signature are considered of different types), so turning a `impl AsyncFnOnce()` into a `impl AsyncFnOnce() + 'static` cannot be expressed as far as I'm aware (as there is no way in telling the resulting `impl AsyncFnOnce() + 'static` have the same size than the `impl AsyncFnOnce()` provided as input)
- On top of that `unsafe_jar::run` relies on `wasm_bindgen::Closure::once` which itself requires the passed closure to be `'static`

### CODE REVIEW

File: src/factory.rs [hunk 1]
```diff
@@ -97,16 +97,12 @@ impl<Err: 'static> Factory<Err> {
...
         &self,
         name: &str,
         version: u32,
-        on_upgrade_needed: Fun,
-    ) -> crate::Result<Database<Err>, Err>
-    where
-        Fun: 'static + FnOnce(VersionChangeEvent<Err>) -> RetFut,
-        RetFut: 'static + Future<Output = crate::Result<(), Err>>,
-    {
+        on_upgrade_needed: impl AsyncFnOnce(VersionChangeEvent<Err>) -> crate::Result<(), Err> + 'static,
```
Comment (Ekleog) [inline src/factory.rs]:
```suggestion
        on_upgrade_needed: impl 'static + AsyncFnOnce(VersionChangeEvent<Err>) -> crate::Result<(), Err>,
```

File: src/transaction.rs [hunk 2]
```diff
@@ -98,11 +98,11 @@ impl<Err> TransactionBuilder<Err> {
     // - If the `Closure` from `transaction_request` has already been dropped, then the callback
     //   will panic. Most likely this will lead to the transaction aborting, but this is an
     //   untested and unsupported code path.
-    pub async fn run<Fun, RetFut, Ret>(self, transaction: Fun) -> crate::Result<Ret, Err>
+    pub async fn run<Ret: 'static>(
+        self,
+        transaction: impl AsyncFnOnce(Transaction<Err>) -> crate::Result<Ret, Err> + 'static,
+    ) -> crate::Result<Ret, Err>
     where
```
Comment (Ekleog) [inline src/transaction.rs]:
```suggestion
    pub async fn run<Ret>(
        self,
        transaction: impl 'static + AsyncFnOnce(Transaction<Err>) -> crate::Result<Ret, Err>,
    ) -> crate::Result<Ret, Err>
    where
        Ret: 'static,
```

**Review by Ekleog — APPROVED** [review]
LGTM! Just two small style nits, I'm committing them to your branch and merging :smile:

**Comment by Ekleog** [comment]
Thank you for the PR! I'll probably release 0.5 after coming to a decision on https://github.com/Ekleog/indexed-db/issues/4 ; and having made enough progress on [sakuhiki](https://github.com/Ekleog/sakuhiki) to be sure the new API works fine for me :smile:
